//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angularjs_Mvc_DelhiRto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Address { get; set; }
        public string PanNumber { get; set; }
        public string Vehicle_Type { get; set; }
        public string Maker { get; set; }
        public Nullable<System.DateTime> YOM { get; set; }
        public string Horse_Power { get; set; }
        public string Cubic_Capacity { get; set; }
        public string Engine_Number { get; set; }
        public string DealerName { get; set; }
    }
}
